font:
  normal:
    family: Cozette
    style: Regular

  bold:
    family: Cozette
    style: Regular

  italic:
    family: Cozette
    style: Regular

  bold_italic:
    family: Cozette
    style: Regular

  size: 10
