import = ["/home/tjbarber/Projects/alacritty-noirbuddy/noirbuddy-miami-nights.toml"]

[font]
size = 14 

# This is the font size we use for screencasting
# size = 40

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 20
y = 20

[keyboard]
bindings = [
  { key = "F", mods = "Command | Shift", action = "ToggleFullscreen" }
]
